version: '3'
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - "/var/lib/grafana"
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: "sensorhub"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "password"
      INFLUXDB_WRITE_USER: "sensor"
      INFLUXDB_WRITE_USER_PASSWORD: "hub"
      INFLUXDB_READ_USER: "grafana"
      INFLUXDB_READ_USER_PASSWORD: "grafana"
    volumes:
      - "/var/lib/influxdb"

